### ISSUE TITLE
Hull in wrong region in MSOA cartogram

### ISSUE THREAD

**Issue by VictimOfMaths** [houseofcommonslibrary/uk-hex-cartograms-noncontiguous#1]
It appears that Kingston upon Hull, City has a RegionNation value of "South West" rather than "Yorkshire and The Humber" for some mysterious reason in the MSOA version of the cartogram (at least, I haven't checked the others).

**Comment by bakerc-hoc** [comment]
Thanks - should be fixed in the latest commit. Let me know if there are any further problems.
