### ISSUE TITLE
Projection error in the UTLA cartogram

### ISSUE THREAD

**Issue by VictimOfMaths** [houseofcommonslibrary/uk-hex-cartograms-noncontiguous#2]
There appears to be an error in the UTLA version of the cartogram where the UTLA 2018 layer has the wrong projection and doesn't align with the other layers. The UTLA 2019 layer is fine.

**Comment by bakerc-hoc** [comment]
Thanks - should be fixed in the latest commit. Let me know if there are any further problems.
