### ISSUE TITLE
Background shape for Wales only

### ISSUE THREAD

**Issue by HywelMJ** [houseofcommonslibrary/uk-hex-cartograms-noncontiguous#5]
Please!

**Comment by bakerc-hoc** [comment]
Good idea - I'll add this to the list (for the new year). I think one might arrange the shapes slightly differently for a Wales-only cartogram but that would be for the future.

**Comment by bakerc-hoc** [comment]
Now added in the latest commit. Let me know if this has any problems.

https://github.com/houseofcommonslibrary/uk-hex-cartograms-noncontiguous/tree/main/geopackages

**Comment by HywelMJ** [comment]
Worked fine thanks. See [https://statiaith.com/blog/yn-gallu-siarad-cymraeg-hecsagonau-msoa/](https://statiaith.com/blog/yn-gallu-siarad-cymraeg-hecsagonau-msoa/)
